# Generated by Django 5.2.5 on 2025-08-17 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissionreview',
            old_name='score_override',
            new_name='score',
        ),
    ]
