# Generated by Django 5.2.5 on 2025-08-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_rename_score_override_submissionreview_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionreview',
            name='score',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
