# Generated by Django 5.2.5 on 2025-08-18 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_alter_submissionreview_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionreview',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='submissions.submission'),
        ),
    ]
