# Generated by Django 5.2.5 on 2025-08-25 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_alter_challenge_challenge_type_and_more'),
        ('submissions', '0005_alter_submissionreview_submission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('graded', 'Graded'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='submissionreview',
            name='reviewed_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', 'challenge'], name='submissions_user_id_08f14c_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status', 'submitted_at'], name='submissions_status_37dcdc_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionfile',
            index=models.Index(fields=['submission'], name='submissions_submiss_3cedac_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionreview',
            index=models.Index(fields=['submission', 'reviewer'], name='submissions_submiss_e4417b_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionreview',
            index=models.Index(fields=['reviewed_at'], name='submissions_reviewe_4b9906_idx'),
        ),
    ]
