# Generated by Django 5.2.5 on 2025-08-13 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_remove_challenge_category_challenge_categories_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='areas_of_expertise',
            field=models.ManyToManyField(blank=True, help_text='Select areas that match your skills and interests', related_name='students', to='challenges.challengecategory'),
        ),
        migrations.CreateModel(
            name='GraduateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=255)),
                ('graduation_year', models.IntegerField()),
                ('current_position', models.CharField(blank=True, max_length=255)),
                ('skills', models.TextField(blank=True)),
                ('areas_of_expertise', models.ManyToManyField(blank=True, help_text='Select areas that match your professional expertise', related_name='graduates', to='challenges.challengecategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graduate_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
