# Generated by Django 5.2.5 on 2025-08-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('challenges', '0006_alter_challenge_challenge_type_and_more'),
        ('users', '0003_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='industry',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='verification_status',
            field=models.CharField(db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('graduate', 'Graduate'), ('company_user', 'Company User'), ('mentor', 'Mentor'), ('admin', 'Admin')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='graduateprofile',
            name='graduation_year',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='availability',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pendingcompanydomain',
            name='domain',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='pendingcompanydomain',
            name='industry',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pendingcompanydomain',
            name='status',
            field=models.CharField(db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='pendingschooldomain',
            name='domain',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='pendingschooldomain',
            name='status',
            field=models.CharField(db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='graduation_year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='companyprofile',
            index=models.Index(fields=['company_name', 'industry'], name='users_compa_company_7ba83d_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role', 'is_verified'], name='users_custo_role_10db6c_idx'),
        ),
        migrations.AddIndex(
            model_name='graduateprofile',
            index=models.Index(fields=['university_name', 'graduation_year'], name='users_gradu_univers_b8d045_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorprofile',
            index=models.Index(fields=['availability'], name='users_mento_availab_4851d6_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingcompanydomain',
            index=models.Index(fields=['company_name', 'industry', 'status'], name='users_pendi_company_d65577_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingschooldomain',
            index=models.Index(fields=['university_name', 'status'], name='users_pendi_univers_f26196_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['university_name'], name='users_stude_univers_020325_idx'),
        ),
    ]
