import requests
import json
from datetime import datetime, timedelta

# API endpoint and token
url = "http://localhost:8000/api/companies/company/challenges/create/"
token = "e749242d5c8080b19612d2e6ff591482ef38bca1"
headers = {
    "Authorization": f"Token {token}",
    "Content-Type": "application/json"
}

# Define 15 challenges covering all challenge types
challenges = [
    {
        "title": "SQL Injection Detection Script",
        "description": "Develop a Python script to detect SQL injection vulnerabilities in a web application. Submit a GitHub repository with your code and a README explaining the approach.",
        "challenge_type": "coding",
        "difficulty": "medium",
        "visibility": "public",
        "categories": [{"name": "Cybersecurity"}],
        "start_date": (datetime.now()).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "end_date": (datetime.now() + timedelta(days=7)).strftime("%Y-%m-%dT23:59:59Z"),
        "max_submissions": 2,
        "skill_tags": "Python, Cybersecurity, Ethical Hacking",
        "learning_outcomes": "Learn to identify and mitigate SQL injection vulnerabilities",
        "prerequisite_description": "Basic knowledge of Python and web security concepts. Mandatory: Submit a GitHub URL with your code and README. No local repository required.",
        "max_score": 100.0,
        "is_published": True
    },
    {
        "title": "Sustainable Fabric Pattern Design",
        "description": "Design eco-friendly fabric patterns for a sustainable clothing line. Submit a PDF with your designs and a brief explanation of your approach.",
        "challenge_type": "design",
        "difficulty": "easy",
        "visibility": "public",
        "categories": [{"name": "Fabric Design"}],
        "start_date": (datetime.now()).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "end_date": (datetime.now() + timedelta(days=10)).strftime("%Y-%m-%dT23:59:59Z"),
        "max_submissions": 3,
        "skill_tags": "Textile Design, Sustainability, Creativity",
        "learning_outcomes": "Learn principles of sustainable design and pattern creation",
        "prerequisite_description": "Basic design skills. Mandatory: Submit a PDF file with designs and explanation. No repository required.",
        "max_score": 100.0,
        "is_published": True
    },
    {
        "title": "Customer Churn Prediction Model",
        "description": "Build a machine learning model to predict customer churn using a provided dataset. Submit a Jupyter Notebook (.ipynb) with your code and a GitHub URL for the project.",
        "challenge_type": "data_analysis",
        "difficulty": "hard",
        "visibility": "public",
        "categories": [{"name": "Machine Learning"}],
        "start_date": (datetime.now()).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "end_date": (datetime.now() + timedelta(days=14)).strftime("%Y-%m-%dT23:59:59Z"),
        "max_submissions": 2,
        "skill_tags": "Python, Machine Learning, Data Analysis",
        "learning_outcomes": "Learn to build and evaluate classification models",
        "prerequisite_description": "Experience with Python, pandas, and scikit-learn. Mandatory: Submit both a Jupyter Notebook (.ipynb) and a GitHub URL with the project.",
        "max_score": 150.0,
        "is_published": True
    },
    {
        "title": "Odoo Inventory Tracking Module",
        "description": "Create a custom Odoo module to track inventory movements in a warehouse. Submit a GitHub repository with the module and documentation.",
        "challenge_type": "coding",
        "difficulty": "expert",
        "visibility": "public",
        "categories": [{"name": "Odoo Development"}],
        "start_date": (datetime.now()).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "end_date": (datetime.now() + timedelta(days=21)).strftime("%Y-%m-%dT23:59:59Z"),
        "max_submissions": 1,
        "skill_tags": "Python, Odoo, ERP",
        "learning_outcomes": "Learn to develop and deploy custom Odoo modules",
        "prerequisite_description": "Knowledge of Python and Odoo framework. Mandatory: Submit a GitHub URL with the module and documentation. No local repository required.",
        "max_score": 200.0,
        "is_published": True
    },
    {
        "title": "Tech Product Sales Pitch",
        "description": "Develop a sales pitch for a new tech product, including market analysis in an Excel file. Submit the Excel file with sales projections.",
        "challenge_type": "sales_pitch",
        "difficulty": "medium",
        "visibility": "public",
        "categories": [{"name": "Sales"}],
        "start_date": (datetime.now()).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "end_date": (datetime.now() + timedelta(days=7)).strftime("%Y-%m-%dT23:59:59Z"),
        "max_submissions": 3,
        "skill_tags": "Sales, Communication, Excel",
        "learning_outcomes": "Learn to craft compelling sales pitches and analyze market data",
        "prerequisite_description": "Basic sales knowledge and Excel proficiency. Mandatory: Submit an Excel file with sales projections. No repository required.",
        "max_score": 100.0,
        "is_published": True
    },
    {
        "title": "Employee Retention Strategy",
        "description": "Design an HR strategy to improve employee retention. Submit a PDF report outlining your plan and key metrics.",
        "challenge_type": "hr_strategy",
        "difficulty": "medium",
        "visibility": "public",
        "categories": [{"name": "HR"}],
        "start_date": (datetime.now()).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "end_date": (datetime.now() + timedelta(days=10)).strftime("%Y-%m-%dT23:59:59Z"),
        "max_submissions": 2,
        "skill_tags": "HR, Employee Engagement, Strategy",
        "learning_outcomes": "Learn to develop effective HR strategies for retention",
        "prerequisite_description": "Basic HR knowledge. Mandatory: Submit a PDF report with retention plan and metrics. No repository required.",
        "max_score": 100.0,
        "is_published": True
    },
    {
        "title": "Financial Forecasting Model",
        "description": "Create a financial forecasting model for a startup using Excel. Submit the Excel file with your model and assumptions.",
        "challenge_type": "financial_analysis",
        "difficulty": "hard",
        "visibility": "public",
        "categories": [{"name": "Accounting"}],
        "start_date": (datetime.now()).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "end_date": (datetime.now() + timedelta(days=14)).strftime("%Y-%m-%dT23:59:59Z"),
        "max_submissions": 2,
        "skill_tags": "Excel, Financial Modeling, Forecasting",
        "learning_outcomes": "Learn to build financial models for startups",
        "prerequisite_description": "Proficiency in Excel and basic accounting. Mandatory: Submit an Excel file with forecasting model and assumptions. No repository required.",
        "max_score": 120.0,
        "is_published": True
    },
    {
        "title": "Social Media Marketing Campaign",
        "description": "Design a social media marketing campaign for a new product launch. Submit a PDF with your campaign plan and a sample post.",
        "challenge_type": "marketing_campaign",
        "difficulty": "medium",
        "visibility": "public",
        "categories": [{"name": "Marketing"}],
        "start_date": (datetime.now()).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "end_date": (datetime.now() + timedelta(days=10)).strftime("%Y-%m-%dT23:59:59Z"),
        "max_submissions": 3,
        "skill_tags": "Marketing, Social Media, Content Creation",
        "learning_outcomes": "Learn to create effective social media campaigns",
        "prerequisite_description": "Basic marketing knowledge. Mandatory: Submit a PDF with campaign plan and sample post. No repository required.",
        "max_score": 100.0,
        "is_published": True
    },
    {
        "title": "E-commerce Case Study",
        "description": "Analyze a failing e-commerce platform and propose solutions. Submit a PDF report with your analysis and recommendations.",
        "challenge_type": "case_study",
        "difficulty": "hard",
        "visibility": "public",
        "categories": [{"name": "Business Analysis"}],
        "start_date": (datetime.now()).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "end_date": (datetime.now() + timedelta(days=14)).strftime("%Y-%m-%dT23:59:59Z"),
        "max_submissions": 2,
        "skill_tags": "Business Analysis, Problem-Solving, Strategy",
        "learning_outcomes": "Learn to analyze business problems and propose solutions",
        "prerequisite_description": "Basic business knowledge. Mandatory: Submit a PDF report with analysis and recommendations. No repository required.",
        "max_score": 120.0,
        "is_published": True
    },
    {
        "title": "Startup Pitch Presentation",
        "description": "Create a pitch deck for a startup idea. Submit a PowerPoint or PDF slide deck with your presentation.",
        "challenge_type": "presentation",
        "difficulty": "medium",
        "visibility": "public",
        "categories": [{"name": "Entrepreneurship"}],
        "start_date": (datetime.now()).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "end_date": (datetime.now() + timedelta(days=7)).strftime("%Y-%m-%dT23:59:59Z"),
        "max_submissions": 2,
        "skill_tags": "Presentation, Pitching, Entrepreneurship",
        "learning_outcomes": "Learn to create compelling pitch decks",
        "prerequisite_description": "Basic presentation skills. Mandatory: Submit a PPT or PDF slide deck. No repository required.",
        "max_score": 100.0,
        "is_published": True
    },
    {
        "title": "Cybersecurity Quiz",
        "description": "Complete a quiz on cybersecurity best practices. Submit answers via a text input form.",
        "challenge_type": "quiz",
        "difficulty": "easy",
        "visibility": "public",
        "categories": [{"name": "Cybersecurity"}],
        "start_date": (datetime.now()).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "end_date": (datetime.now() + timedelta(days=5)).strftime("%Y-%m-%dT23:59:59Z"),
        "max_submissions": 1,
        "skill_tags": "Cybersecurity, Knowledge Testing",
        "learning_outcomes": "Learn cybersecurity best practices",
        "prerequisite_description": "Basic cybersecurity knowledge. Mandatory: Submit answers via text input. No file or repository required.",
        "max_score": 50.0,
        "is_published": True
    },
    {
        "title": "Customer Service Simulation",
        "description": "Simulate handling customer complaints for a retail company. Submit a video recording of your response.",
        "challenge_type": "simulation",
        "difficulty": "medium",
        "visibility": "public",
        "categories": [{"name": "Customer Service"}],
        "start_date": (datetime.now()).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "end_date": (datetime.now() + timedelta(days=7)).strftime("%Y-%m-%dT23:59:59Z"),
        "max_submissions": 2,
        "skill_tags": "Customer Service, Communication, Problem-Solving",
        "learning_outcomes": "Learn to handle customer complaints effectively",
        "prerequisite_description": "Basic communication skills. Mandatory: Submit a video file (MP4). No repository required.",
        "max_score": 100.0,
        "is_published": True
    },
    {
        "title": "Product Launch Story",
        "description": "Write a creative story about a product launch for a tech startup. Submit a text document with your story.",
        "challenge_type": "creative_writing",
        "difficulty": "easy",
        "visibility": "public",
        "categories": [{"name": "Marketing"}],
        "start_date": (datetime.now()).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "end_date": (datetime.now() + timedelta(days=7)).strftime("%Y-%m-%dT23:59:59Z"),
        "max_submissions": 3,
        "skill_tags": "Creative Writing, Storytelling, Marketing",
        "learning_outcomes": "Learn to craft engaging marketing stories",
        "prerequisite_description": "Basic writing skills. Mandatory: Submit a text document (DOCX or text input). No repository required.",
        "max_score": 80.0,
        "is_published": True
    },
    {
        "title": "Agile Project Plan",
        "description": "Create an Agile project plan for developing a mobile app. Submit a PDF with your plan, including sprints and tasks.",
        "challenge_type": "project_management",
        "difficulty": "hard",
        "visibility": "public",
        "categories": [{"name": "Project Management"}],
        "start_date": (datetime.now()).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "end_date": (datetime.now() + timedelta(days=14)).strftime("%Y-%m-%dT23:59:59Z"),
        "max_submissions": 2,
        "skill_tags": "Agile, Project Management, Planning",
        "learning_outcomes": "Learn Agile project management methodologies",
        "prerequisite_description": "Knowledge of Agile principles. Mandatory: Submit a PDF plan with sprints and tasks. No repository required.",
        "max_score": 120.0,
        "is_published": True
    },
    {
        "title": "Market Research Report",
        "description": "Conduct market research on the electric vehicle industry. Submit a PDF report with your findings and analysis.",
        "challenge_type": "research",
        "difficulty": "hard",
        "visibility": "public",
        "categories": [{"name": "Market Research"}],
        "start_date": (datetime.now()).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "end_date": (datetime.now() + timedelta(days=14)).strftime("%Y-%m-%dT23:59:59Z"),
        "max_submissions": 2,
        "skill_tags": "Research, Analysis, Report Writing",
        "learning_outcomes": "Learn to conduct and present market research",
        "prerequisite_description": "Basic research skills. Mandatory: Submit a PDF report with findings and analysis. No repository required.",
        "max_score": 120.0,
        "is_published": True
    },
    {
        "title": "Product Explainer Video",
        "description": "Create a short explainer video for a new software product. Submit the video file.",
        "challenge_type": "video_production",
        "difficulty": "medium",
        "visibility": "public",
        "categories": [{"name": "Marketing"}],
        "start_date": (datetime.now()).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "end_date": (datetime.now() + timedelta(days=10)).strftime("%Y-%m-%dT23:59:59Z"),
        "max_submissions": 2,
        "skill_tags": "Video Production, Storytelling, Marketing",
        "learning_outcomes": "Learn to create engaging explainer videos",
        "prerequisite_description": "Basic video editing skills. Mandatory: Submit a video file (MP4). No repository required.",
        "max_score": 100.0,
        "is_published": True
    },
    {
        "title": "Business Strategy Consulting",
        "description": "Propose a growth strategy for a small business. Submit a PDF with your consulting report.",
        "challenge_type": "consulting",
        "difficulty": "expert",
        "visibility": "public",
        "categories": [{"name": "Business Analysis"}],
        "start_date": (datetime.now()).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "end_date": (datetime.now() + timedelta(days=21)).strftime("%Y-%m-%dT23:59:59Z"),
        "max_submissions": 1,
        "skill_tags": "Consulting, Strategy, Business Analysis",
        "learning_outcomes": "Learn to develop business growth strategies",
        "prerequisite_description": "Advanced business knowledge. Mandatory: Submit a PDF report with growth strategy. No repository required.",
        "max_score": 150.0,
        "is_published": True
    },
    {
        "title": "Smartwatch App Prototype",
        "description": "Design a prototype for a smartwatch fitness app. Submit a Figma or PDF mockup of the UI/UX.",
        "challenge_type": "product_design",
        "difficulty": "medium",
        "visibility": "public",
        "categories": [{"name": "Product Design"}],
        "start_date": (datetime.now()).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "end_date": (datetime.now() + timedelta(days=10)).strftime("%Y-%m-%dT23:59:59Z"),
        "max_submissions": 2,
        "skill_tags": "UI/UX, Product Design, Prototyping",
        "learning_outcomes": "Learn to design user-friendly app prototypes",
        "prerequisite_description": "Basic UI/UX design skills. Mandatory: Submit a Figma link or PDF mockup. No repository required.",
        "max_score": 100.0,
        "is_published": True
    },
    {
        "title": "Open-Source Contribution Guide",
        "description": "Create a guide for contributing to an open-source project. Submit a text document with your guide.",
        "challenge_type": "document",
        "difficulty": "easy",
        "visibility": "public",
        "categories": [{"name": "Developers"}],
        "start_date": (datetime.now()).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "end_date": (datetime.now() + timedelta(days=7)).strftime("%Y-%m-%dT23:59:59Z"),
        "max_submissions": 3,
        "skill_tags": "Technical Writing, Open Source, Documentation",
        "learning_outcomes": "Learn to write clear technical documentation",
        "prerequisite_description": "Basic writing skills. Mandatory: Submit a text document (DOCX or text input). No repository required.",
        "max_score": 80.0,
        "is_published": True
    },
    {
        "title": "Custom API Integration",
        "description": "Integrate a third-party API into a web app. Submit a GitHub repository with your code and documentation.",
        "challenge_type": "other",
        "difficulty": "hard",
        "visibility": "public",
        "categories": [{"name": "Developers"}],
        "start_date": (datetime.now()).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "end_date": (datetime.now() + timedelta(days=14)).strftime("%Y-%m-%dT23:59:59Z"),
        "max_submissions": 2,
        "skill_tags": "API Integration, Python, Web Development",
        "learning_outcomes": "Learn to integrate and test third-party APIs",
        "prerequisite_description": "Knowledge of Python and REST APIs. Mandatory: Submit a GitHub URL with code and documentation. No local repository required.",
        "max_score": 120.0,
        "is_published": True
    },
       # Developers - 2 additional challenges
    {
        "title": "RESTful API for Task Management",
        "description": "Develop a RESTful API for a task management system using Django and Django REST Framework. Submit a GitHub repository with the API code and documentation.",
        "challenge_type": "coding",
        "difficulty": "medium",
        "visibility": "public",
        "categories": [{"name": "Developers"}],
        "start_date": (datetime.now()).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "end_date": (datetime.now() + timedelta(days=14)).strftime("%Y-%m-%dT23:59:59Z"),
        "max_submissions": 2,
        "skill_tags": "Python, Django, REST API",
        "learning_outcomes": "Learn to build and document RESTful APIs",
        "prerequisite_description": "Knowledge of Python and Django. Mandatory: Submit a GitHub URL with code and documentation. No local repository required.",
        "max_score": 120.0,
        "is_published": True
    },
    {
        "title": "Unit Testing Suite for Web App",
        "description": "Create a comprehensive unit testing suite for a sample web application using pytest. Submit a GitHub repository with the test code and a coverage report.",
        "challenge_type": "coding",
        "difficulty": "hard",
        "visibility": "public",
        "categories": [{"name": "Developers"}],
        "start_date": (datetime.now()).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "end_date": (datetime.now() + timedelta(days=14)).strftime("%Y-%m-%dT23:59:59Z"),
        "max_submissions": 2,
        "skill_tags": "Python, Pytest, Testing",
        "learning_outcomes": "Learn to write effective unit tests and measure code coverage",
        "prerequisite_description": "Experience with Python and testing frameworks. Mandatory: Submit a GitHub URL with test code and coverage report. No local repository required.",
        "max_score": 130.0,
        "is_published": True
    },
    # HR - 2 additional challenges
    {
        "title": "Recruitment Process Optimization",
        "description": "Design a streamlined recruitment process for a tech startup. Submit a PDF report detailing the process and tools recommended.",
        "challenge_type": "hr_strategy",
        "difficulty": "medium",
        "visibility": "public",
        "categories": [{"name": "HR"}],
        "start_date": (datetime.now()).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "end_date": (datetime.now() + timedelta(days=10)).strftime("%Y-%m-%dT23:59:59Z"),
        "max_submissions": 2,
        "skill_tags": "HR, Recruitment, Process Design",
        "learning_outcomes": "Learn to optimize recruitment workflows",
        "prerequisite_description": "Basic HR knowledge. Mandatory: Submit a PDF report with process details. No repository required.",
        "max_score": 100.0,
        "is_published": True
    },
    {
        "title": "Employee Onboarding Program",
        "description": "Create an onboarding program for new hires, including a 30-60-90 day plan. Submit a PDF with the program outline and resources.",
        "challenge_type": "hr_strategy",
        "difficulty": "easy",
        "visibility": "public",
        "categories": [{"name": "HR"}],
        "start_date": (datetime.now()).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "end_date": (datetime.now() + timedelta(days=7)).strftime("%Y-%m-%dT23:59:59Z"),
        "max_submissions": 3,
        "skill_tags": "HR, Onboarding, Employee Engagement",
        "learning_outcomes": "Learn to design effective onboarding programs",
        "prerequisite_description": "Basic HR knowledge. Mandatory: Submit a PDF with onboarding plan. No repository required.",
        "max_score": 80.0,
        "is_published": True
    },
    # Sales - 2 additional challenges
    {
        "title": "B2B Sales Strategy",
        "description": "Develop a B2B sales strategy for a SaaS product. Submit a PDF with your strategy and key performance indicators.",
        "challenge_type": "sales_pitch",
        "difficulty": "hard",
        "visibility": "public",
        "categories": [{"name": "Sales"}],
        "start_date": (datetime.now()).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "end_date": (datetime.now() + timedelta(days=14)).strftime("%Y-%m-%dT23:59:59Z"),
        "max_submissions": 2,
        "skill_tags": "Sales, B2B, Strategy",
        "learning_outcomes": "Learn to develop effective B2B sales strategies",
        "prerequisite_description": "Knowledge of sales processes. Mandatory: Submit a PDF with strategy and KPIs. No repository required.",
        "max_score": 120.0,
        "is_published": True
    },
    {
        "title": "Cold Call Script",
        "description": "Write a cold call script for selling a new software solution. Submit a text document with the script and a brief explanation.",
        "challenge_type": "sales_pitch",
        "difficulty": "easy",
        "visibility": "public",
        "categories": [{"name": "Sales"}],
        "start_date": (datetime.now()).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "end_date": (datetime.now() + timedelta(days=7)).strftime("%Y-%m-%dT23:59:59Z"),
        "max_submissions": 3,
        "skill_tags": "Sales, Communication, Scripting",
        "learning_outcomes": "Learn to craft persuasive cold call scripts",
        "prerequisite_description": "Basic sales knowledge. Mandatory: Submit a text document (DOCX or text input). No repository required.",
        "max_score": 80.0,
        "is_published": True
    },
    # Accounting - 2 additional challenges
    {
        "title": "Budget Analysis for Non-Profit",
        "description": "Analyze a non-profit organization's budget and propose cost-saving measures. Submit an Excel file with your analysis and recommendations.",
        "challenge_type": "financial_analysis",
        "difficulty": "medium",
        "visibility": "public",
        "categories": [{"name": "Accounting"}],
        "start_date": (datetime.now()).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "end_date": (datetime.now() + timedelta(days=10)).strftime("%Y-%m-%dT23:59:59Z"),
        "max_submissions": 2,
        "skill_tags": "Excel, Budgeting, Accounting",
        "learning_outcomes": "Learn to analyze budgets and propose optimizations",
        "prerequisite_description": "Proficiency in Excel and accounting principles. Mandatory: Submit an Excel file with analysis. No repository required.",
        "max_score": 100.0,
        "is_published": True
    },
    {
        "title": "Cash Flow Projection",
        "description": "Create a 12-month cash flow projection for a small business. Submit an Excel file with your projections and assumptions.",
        "challenge_type": "financial_analysis",
        "difficulty": "hard",
        "visibility": "public",
        "categories": [{"name": "Accounting"}],
        "start_date": (datetime.now()).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "end_date": (datetime.now() + timedelta(days=14)).strftime("%Y-%m-%dT23:59:59Z"),
        "max_submissions": 2,
        "skill_tags": "Excel, Cash Flow, Accounting",
        "learning_outcomes": "Learn to create accurate cash flow projections",
        "prerequisite_description": "Knowledge of accounting and Excel. Mandatory: Submit an Excel file with projections. No repository required.",
        "max_score": 120.0,
        "is_published": True
    },
    # Entrepreneurship - 1 additional challenge
    {
        "title": "Business Model Canvas",
        "description": "Create a business model canvas for a new startup idea. Submit a PDF with your canvas and a brief explanation.",
        "challenge_type": "presentation",
        "difficulty": "medium",
        "visibility": "public",
        "categories": [{"name": "Entrepreneurship"}],
        "start_date": (datetime.now()).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "end_date": (datetime.now() + timedelta(days=10)).strftime("%Y-%m-%dT23:59:59Z"),
        "max_submissions": 2,
        "skill_tags": "Entrepreneurship, Business Planning, Strategy",
        "learning_outcomes": "Learn to develop a business model canvas",
        "prerequisite_description": "Basic business knowledge. Mandatory: Submit a PDF with canvas and explanation. No repository required.",
        "max_score": 100.0,
        "is_published": True
    },
    # Customer Service - 1 additional challenge
    {
        "title": "Customer Feedback Analysis",
        "description": "Analyze customer feedback data and propose improvements. Submit a PDF report with your analysis and recommendations.",
        "challenge_type": "case_study",
        "difficulty": "medium",
        "visibility": "public",
        "categories": [{"name": "Customer Service"}],
        "start_date": (datetime.now()).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "end_date": (datetime.now() + timedelta(days=10)).strftime("%Y-%m-%dT23:59:59Z"),
        "max_submissions": 2,
        "skill_tags": "Customer Service, Analysis, Communication",
        "learning_outcomes": "Learn to analyze customer feedback and improve service",
        "prerequisite_description": "Basic analytical skills. Mandatory: Submit a PDF report with analysis. No repository required.",
        "max_score": 100.0,
        "is_published": True
    },
    # Project Management - 1 additional challenge
    {
        "title": "Risk Management Plan",
        "description": "Develop a risk management plan for a software development project. Submit a PDF with your plan and mitigation strategies.",
        "challenge_type": "project_management",
        "difficulty": "medium",
        "visibility": "public",
        "categories": [{"name": "Project Management"}],
        "start_date": (datetime.now()).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "end_date": (datetime.now() + timedelta(days=10)).strftime("%Y-%m-%dT23:59:59Z"),
        "max_submissions": 2,
        "skill_tags": "Project Management, Risk Analysis, Planning",
        "learning_outcomes": "Learn to identify and mitigate project risks",
        "prerequisite_description": "Knowledge of project management principles. Mandatory: Submit a PDF with risk plan. No repository required.",
        "max_score": 100.0,
        "is_published": True
    },
    # Market Research - 1 additional challenge
    {
        "title": "Competitor Analysis Report",
        "description": "Conduct a competitor analysis for a retail brand. Submit a PDF report with your findings and strategic recommendations.",
        "challenge_type": "research",
        "difficulty": "hard",
        "visibility": "public",
        "categories": [{"name": "Market Research"}],
        "start_date": (datetime.now()).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "end_date": (datetime.now() + timedelta(days=14)).strftime("%Y-%m-%dT23:59:59Z"),
        "max_submissions": 2,
        "skill_tags": "Research, Analysis, Strategy",
        "learning_outcomes": "Learn to perform competitor analysis and develop strategies",
        "prerequisite_description": "Basic research skills. Mandatory: Submit a PDF report with findings. No repository required.",
        "max_score": 120.0,
        "is_published": True
    },
    # Product Design - 1 additional challenge
    {
        "title": "Mobile App Wireframe",
        "description": "Design wireframes for a mobile app focused on e-learning. Submit a Figma link or PDF with your wireframes.",
        "challenge_type": "product_design",
        "difficulty": "medium",
        "visibility": "public",
        "categories": [{"name": "Product Design"}],
        "start_date": (datetime.now()).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "end_date": (datetime.now() + timedelta(days=10)).strftime("%Y-%m-%dT23:59:59Z"),
        "max_submissions": 2,
        "skill_tags": "UI/UX, Wireframing, Product Design",
        "learning_outcomes": "Learn to create user-friendly wireframes",
        "prerequisite_description": "Basic UI/UX design skills. Mandatory: Submit a Figma link or PDF with wireframes. No repository required.",
        "max_score": 100.0,
        "is_published": True
    },
    # Machine Learning - 1 additional challenge
    {
        "title": "Sentiment Analysis Model",
        "description": "Build a sentiment analysis model for social media posts using NLP. Submit a Jupyter Notebook and GitHub URL with your code.",
        "challenge_type": "data_analysis",
        "difficulty": "hard",
        "visibility": "public",
        "categories": [{"name": "Machine Learning"}],
        "start_date": (datetime.now()).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "end_date": (datetime.now() + timedelta(days=14)).strftime("%Y-%m-%dT23:59:59Z"),
        "max_submissions": 2,
        "skill_tags": "Python, NLP, Machine Learning",
        "learning_outcomes": "Learn to build and evaluate NLP models",
        "prerequisite_description": "Experience with Python and NLP libraries. Mandatory: Submit a Jupyter Notebook (.ipynb) and GitHub URL. No local repository required.",
        "max_score": 150.0,
        "is_published": True
    },
    # Fabric Design - 1 additional challenge
    {
        "title": "Textile Print for Activewear",
        "description": "Design a textile print for eco-friendly activewear. Submit a PDF with your designs and material specifications.",
        "challenge_type": "design",
        "difficulty": "medium",
        "visibility": "public",
        "categories": [{"name": "Fabric Design"}],
        "start_date": (datetime.now()).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "end_date": (datetime.now() + timedelta(days=10)).strftime("%Y-%m-%dT23:59:59Z"),
        "max_submissions": 3,
        "skill_tags": "Textile Design, Sustainability, Creativity",
        "learning_outcomes": "Learn to design functional textile prints",
        "prerequisite_description": "Basic design skills. Mandatory: Submit a PDF with designs and specs. No repository required.",
        "max_score": 100.0,
        "is_published": True
    },
    # Odoo Development - 1 additional challenge
    {
        "title": "Odoo CRM Customization",
        "description": "Customize the Odoo CRM module to include custom fields for a sales team. Submit a GitHub repository with the module and documentation.",
        "challenge_type": "coding",
        "difficulty": "expert",
        "visibility": "public",
        "categories": [{"name": "Odoo Development"}],
        "start_date": (datetime.now()).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "end_date": (datetime.now() + timedelta(days=21)).strftime("%Y-%m-%dT23:59:59Z"),
        "max_submissions": 1,
        "skill_tags": "Python, Odoo, CRM",
        "learning_outcomes": "Learn to customize Odoo CRM modules",
        "prerequisite_description": "Knowledge of Python and Odoo. Mandatory: Submit a GitHub URL with module and documentation. No local repository required.",
        "max_score": 200.0,
        "is_published": True
    },
    # New Category: Data Science
    {
        "title": "Data Visualization Dashboard",
        "description": "Create an interactive data visualization dashboard using Tableau or Power BI. Submit a PDF with screenshots and a description of your dashboard.",
        "challenge_type": "data_analysis",
        "difficulty": "medium",
        "visibility": "public",
        "categories": [{"name": "Data Science"}],
        "start_date": (datetime.now()).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "end_date": (datetime.now() + timedelta(days=10)).strftime("%Y-%m-%dT23:59:59Z"),
        "max_submissions": 2,
        "skill_tags": "Data Visualization, Tableau, Power BI",
        "learning_outcomes": "Learn to create interactive data dashboards",
        "prerequisite_description": "Experience with Tableau or Power BI. Mandatory: Submit a PDF with screenshots and description. No repository required.",
        "max_score": 100.0,
        "is_published": True
    },
    {
        "title": "Statistical Analysis Report",
        "description": "Perform statistical analysis on a provided dataset using R or Python. Submit a PDF report with your findings and code snippets.",
        "challenge_type": "data_analysis",
        "difficulty": "hard",
        "visibility": "public",
        "categories": [{"name": "Data Science"}],
        "start_date": (datetime.now()).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "end_date": (datetime.now() + timedelta(days=14)).strftime("%Y-%m-%dT23:59:59Z"),
        "max_submissions": 2,
        "skill_tags": "R, Python, Statistics",
        "learning_outcomes": "Learn to perform and present statistical analysis",
        "prerequisite_description": "Knowledge of R or Python and statistics. Mandatory: Submit a PDF report with findings and code. No repository required.",
        "max_score": 120.0,
        "is_published": True
    },
    # New Category: UI/UX Design
    {
        "title": "Website Redesign Mockup",
        "description": "Redesign the homepage of a corporate website for better user experience. Submit a Figma link or PDF with your mockup.",
        "challenge_type": "design",
        "difficulty": "medium",
        "visibility": "public",
        "categories": [{"name": "UI/UX Design"}],
        "start_date": (datetime.now()).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "end_date": (datetime.now() + timedelta(days=10)).strftime("%Y-%m-%dT23:59:59Z"),
        "max_submissions": 2,
        "skill_tags": "UI/UX, Figma, Web Design",
        "learning_outcomes": "Learn to design user-friendly website interfaces",
        "prerequisite_description": "Basic UI/UX design skills. Mandatory: Submit a Figma link or PDF mockup. No repository required.",
        "max_score": 100.0,
        "is_published": True
    },
    {
        "title": "User Flow for E-commerce App",
        "description": "Create a user flow diagram for an e-commerce mobile app. Submit a PDF with your diagram and annotations.",
        "challenge_type": "design",
        "difficulty": "medium",
        "visibility": "public",
        "categories": [{"name": "UI/UX Design"}],
        "start_date": (datetime.now()).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "end_date": (datetime.now() + timedelta(days=10)).strftime("%Y-%m-%dT23:59:59Z"),
        "max_submissions": 2,
        "skill_tags": "UI/UX, User Flows, Prototyping",
        "learning_outcomes": "Learn to design effective user flows",
        "prerequisite_description": "Basic UI/UX design knowledge. Mandatory: Submit a PDF with user flow diagram. No repository required.",
        "max_score": 100.0,
        "is_published": True
    },
]

# Send each challenge as a separate POST request
for challenge in challenges:
    try:
        response = requests.post(url, headers=headers, data=json.dumps(challenge))
        if response.status_code == 201:
            print(f"Successfully created challenge: {challenge['title']}")
        elif response.status_code == 400 and "title" in response.json().get("errors", {}):
            print(f"Challenge already exists, skipping: {challenge['title']}")
        else:
            print(f"Failed to create challenge: {challenge['title']}, Status: {response.status_code}, Error: {response.text}")
    except requests.exceptions.RequestException as e:
        print(f"Error creating challenge {challenge['title']}: {e}")