# Generated by Django 5.2.5 on 2025-08-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_remove_challenge_category_challenge_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='is_featured',
            field=models.BooleanField(blank=True, default=False, help_text='Mark as featured for dashboard carousel', null=True),
        ),
    ]
