# Generated by Django 5.2.5 on 2025-08-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_challenge_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail image for the challenge', null=True, upload_to='challenges/thumbnails/'),
        ),
    ]
