# Generated by Django 5.2.5 on 2025-08-25 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_challenge_thumbnail'),
        ('companies', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='challenge_type',
            field=models.CharField(choices=[('coding', 'Coding'), ('design', 'Design'), ('document', 'Document'), ('data_analysis', 'Data Analysis'), ('case_study', 'Case Study'), ('presentation', 'Presentation'), ('quiz', 'Quiz'), ('simulation', 'Simulation'), ('creative_writing', 'Creative Writing'), ('project_management', 'Project Management'), ('financial_analysis', 'Financial Analysis'), ('marketing_campaign', 'Marketing Campaign'), ('sales_pitch', 'Sales Pitch'), ('hr_strategy', 'HR Strategy'), ('research', 'Research'), ('video_production', 'Video Production'), ('consulting', 'Consulting'), ('product_design', 'Product Design'), ('other', 'Other')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('expert', 'Expert')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='end_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='is_featured',
            field=models.BooleanField(blank=True, db_index=True, default=False, help_text='Mark as featured for dashboard carousel', null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='start_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('company', 'Company-Specific'), ('group', 'Group-Specific')], db_index=True, default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='challengecategory',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='challengefeedback',
            name='rating',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='challengegroup',
            name='is_role_based',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='challengegroup',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='challengerubric',
            name='criterion',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['is_published', 'visibility'], name='challenges__is_publ_f3a328_idx'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['company', 'created_by'], name='challenges__company_3a60b2_idx'),
        ),
        migrations.AddIndex(
            model_name='challengeattachment',
            index=models.Index(fields=['challenge', 'is_required'], name='challenges__challen_c1ee1e_idx'),
        ),
        migrations.AddIndex(
            model_name='challengecategory',
            index=models.Index(fields=['name'], name='challenges__name_0823ed_idx'),
        ),
        migrations.AddIndex(
            model_name='challengefeedback',
            index=models.Index(fields=['challenge', 'user'], name='challenges__challen_005e87_idx'),
        ),
        migrations.AddIndex(
            model_name='challengefeedback',
            index=models.Index(fields=['rating'], name='challenges__rating_7485e9_idx'),
        ),
        migrations.AddIndex(
            model_name='challengegroup',
            index=models.Index(fields=['challenge', 'is_role_based'], name='challenges__challen_8c5b06_idx'),
        ),
        migrations.AddIndex(
            model_name='challengeprerequisite',
            index=models.Index(fields=['challenge', 'prerequisite_challenge'], name='challenges__challen_948921_idx'),
        ),
        migrations.AddIndex(
            model_name='challengerubric',
            index=models.Index(fields=['challenge', 'criterion'], name='challenges__challen_372ef4_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['challenge', 'order'], name='challenges__challen_3ae700_idx'),
        ),
    ]
