name: SkillProof
description: "Show your Experience"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  provider: ^6.1.2
  flutter_secure_storage: ^9.2.2
  file_picker: ^10.3.1
  font_awesome_flutter: ^10.7.0
  carousel_slider: ^5.0.0
  fl_chart: ^1.0.0
  flutter_typeahead: 5.2.0
  flutter_heatmap_calendar: ^1.0.5
  intl: ^0.20.2
  image_cropper: ^9.1.0
  image_picker: ^1.2.0
  fluttertoast: ^8.2.12
  appearance: ^0.0.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.13.1"


flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"