# Generated by Django 5.2.5 on 2025-08-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_score', models.FloatField(blank=True, null=True)),
                ('rubric_breakdown', models.JSONField(blank=True, null=True)),
                ('ai_feedback', models.TextField(blank=True)),
                ('human_override', models.BooleanField(default=False)),
                ('final_score', models.FloatField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=100)),
                ('result', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.JSONField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
