# Generated by Django 5.2.5 on 2025-08-12 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0002_initial'),
        ('evaluations', '0001_initial'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='submissions.submission'),
        ),
        migrations.AddField(
            model_name='evaluationlog',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluation'),
        ),
        migrations.AddField(
            model_name='evaluationrubric',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challenge'),
        ),
    ]
